AllCops:
  NewCops: enable

Layout:
  Enabled: false
Metrics:
  Enabled: false

Style/TrailingCommaInHashLiteral:  # Disabled for rufo
  Enabled: false

Style/StringLiterals:  # Disabled for rufo
  Enabled: false

Style/TrailingCommaInArguments:  # Disabled for rufo
  Enabled: false

Style/StringLiteralsInInterpolation:  # Disabled for rufo
  Enabled: false

Style/StringConcatenation:  # + looks better
  Enabled: false

Lint/MissingSuper:  # For abstract classes
  Enabled: false

Lint/AssignmentInCondition:  # Looks bad
  Enabled: false

Style/PerlBackrefs:  # It will be longer
  Enabled: false

Style/RedundantSelf:  # Looks local variable
  Enabled: false

Naming/VariableNumber:  # Discord API docs naming
  Enabled: false

Style/ParallelAssignment:  # It will be longer
  Enabled: false

Style/RedundantInterpolation:  # For make it extendable
  Enabled: false

Style/Next:  # For make it extendable
  Enabled: false

Lint/ShadowedException:  # False positive
  Enabled: false

Lint/AmbiguousOperatorPrecedence:  # Not needed
  Enabled: false

Style/GlobalVars: # For /exe
  Enabled: false