AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

require:
- rubocop-rake
- rubocop-rspec

# Layout:
#   Enabled: false
Metrics:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentationWidth:
  AllowedPatterns: ['if']

Layout/HeredocIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Style/TrailingCommaInHashLiteral:  # Disabled for rufo
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:  # Disabled for rufo
  EnforcedStyleForMultiline: consistent_comma

Style/StringLiterals:  # Disabled for rufo
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:  # Disabled for rufo
  Enabled: false

Style/StringLiteralsInInterpolation:  # Disabled for rufo
  Enabled: false

Layout/SpaceAroundOperators:  # Changed for rufo
  EnforcedStyleForExponentOperator: space

Style/StringConcatenation:  # + looks better
  Enabled: false

Lint/MissingSuper:  # For abstract classes
  Enabled: false

Lint/AssignmentInCondition:  # Looks bad
  Enabled: false

Style/PerlBackrefs:  # It will be longer
  Enabled: false

Style/RedundantSelf:  # Looks local variable
  Enabled: false

Naming/VariableNumber:  # Discord API docs naming
  Enabled: false

Style/ParallelAssignment:  # It will be longer
  Enabled: false

Style/RedundantInterpolation:  # For make it extendable
  Enabled: false

Style/Next:  # For make it extendable
  Enabled: false

Lint/ShadowedException:  # False positive
  Enabled: false

Lint/AmbiguousOperatorPrecedence:  # Not needed
  Enabled: false

Style/GlobalVars: # For /exe
  Enabled: false

Lint/Debugger: # For /exe
  Enabled: false

Style/GuardClause: # For make it extendable
  Enabled: false

Lint/ScriptPermission: # For GitHub Actions
  Enabled: false

Style/NumericLiterals:  # For style
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false