blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://discorb-lib.github.io/
    about: Read the documentation first.
  - name: Official Guild
    url: https://discord.gg/hCP6zq8Vpj
    about: Join the official Guild.