# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses:
        ruby-version: 3.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Clone repository 
      run: |
        git clone https://github.com/discorb-lib/discorb main-tmp
    - name: Build document
      run: |
        cd main-tmp
        bundle config --local with 'docs'
        bundle install
        bundle exec rake document:build_all
    - name: Commit changes
      run: |
        cd ..
        cp -r main-tmp/doc/. .
        git config --global user.name "sevenc-nanashi"
        git config --global user.email "sevenc_nanashi@yahoo.co.jp"
        git add -A
        git commit -m "Update: Update document"
        git push
      
